### ISSUE TITLE
Please create a MEETINGS.md page with the following content

### ISSUE THREAD

**Issue by dj1k** [fluxcd/gitops-working-group#41]
Please create the below page in / with the content following the line.
---
# GitOps Working Group Meetings
Please find meetings of the GitOps Working Group available below. The next meeting will be listed at the top of the list with links to recordings of past meetings available below (when possible). Times listed are GMT.

#### Thursday, December 10th at 17:00 GMT
- [Video Conference Link](https://weaveworks.zoom.us/j/92771757748)
- Meeting ID: 927 7175 7748

<br><br><br>

---
### GitOps Working Group Meeting Conduct
Please join the video conference with your video turned on and your microphone muted. Meetings should be recorded whenever possible. The GitOps Working Group will follow the CNCF [Openness Guidelines](https://www.cncf.io/blog/2019/06/11/cncf-openness-guidelines/) and The Linux Foundation's [Code of Conduct](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/code-of-conduct/).

**Comment by todaywasawesome** [comment]
Created and waiting approval https://github.com/fluxcd/gitops-working-group/pull/43

**Comment by todaywasawesome** [comment]
Merged https://github.com/fluxcd/gitops-working-group/blob/main/MEETINGS.md

**Comment by torstenwalter** [comment]
@dj1k I think this can be closed.

**Comment by dj1k** [comment]
closed with PR 43.
