### ISSUE TITLE
Enable GitHub Disucssions

### ISSUE THREAD

**Issue by scottrigby** [fluxcd/gitops-working-group#45]
Discussions were mentioned in the call today. 

Seems fitting to enable those on this repo (as opposed to the shared [flux discussions](https://github.com/fluxcd/flux2/discussions/)), since the intent is to move this repo to a new org.

**Comment by stefanprodan** [comment]
done!

**Comment by scottrigby** [comment]
See [slack chat](https://cloud-native.slack.com/archives/C01G9DEE88M/p1607623839023600) with @dj1k. Summary is we may want to wait given that we may be able to move this repo within the next few days. OTOH since there were 45 people on the call today, we may want to capture the swell of interest by going ahead and getting that started (they will carry over automatically when the repo is moved).

**Comment by todaywasawesome** [comment]
@scottrigby will this migrate when we have it under the sig-app delivery git?

**Comment by hiddeco** [comment]
Given it has been made available to all of our repositories, I think the feature is in public beta now and you no longer have to request and/or be granted access to it on a per repository basis.

**Comment by scottrigby** [comment]
Yes it will, because of what @hiddeco just said 👍

**Comment by hiddeco** [comment]
Closing as this has been taken care of.
