### ISSUE TITLE
Add details on how to participate

### ISSUE THREAD

**Issue by tabern** [fluxcd/gitops-working-group#6]
We should have more details on how to participate

Rough ideas:
* join an upcoming meeting
* open an issue with your thoughts on GitOps
* create a PR with suggestions

**Comment by monadic** [comment]
All are valid imho.  We should have a baseline of a community call every two weeks.

**Comment by dj1k** [comment]
All valid - I've just been fighting with the DCO monsters to get changes in. Think I've finally got it figured out...

**Comment by o6uoq** [comment]
Subscribed to this issue and raised https://github.com/fluxcd/gitops-working-group/issues/9

**Comment by dj1k** [comment]
The first community call is scheduled for December 10 at 5pm GMT. More info to come soon.
